spring.application.name=agencia-viagens

spring.datasource.url=jdbc:postgresql://localhost:5432/agencia-viagens
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=aGfA+Wm3G18JyZ3fbW7sJPRhgPjPYA9PP80aA7Sztto=
jwt.expiration-ms=3600000